### PR TITLE
Use max(raw, ema) for the HSL no-restart trigger in Rust and live

### PR DESCRIPTION
**Pull request by enarjord**
First behavior slice of the clarified episode/RED/no-restart contract (#1122, plan B2.1). The permanent no-restart halt now trips on `max(drawdown_raw, drawdown_ema) >= hsl_no_restart_drawdown_threshold` in **both** live and backtest; previously both evaluated raw drawdown only, under-triggering whenever sustained smoothed damage exceeded the instantaneous drawdown at the stop sample (e.g., deep drawdown with partial recovery right before the scope flattened). The RED/panic-now trigger is **unchanged**: recon showed the shared Rust runtime already implements the contract's `min(raw, ema)` tier score — this PR pins that with a regression test instead of touching it.

Centralization (per the guiding contract added in #1124): the predicate is owned by Rust and consumed by both paths —

- `ehsl::no_restart_triggered(policy, drawdown_raw, drawdown_ema, threshold)` in the shared `equity_hard_stop_loss` module, with the policy semantics unchanged (`always` → never latch, `never` → always latch, `threshold` → the max comparison).
- Backtest: `hsl_no_restart_latched` delegates to it; `HardStopStep` and the backtest stop snapshots now carry `drawdown_ema` (populated from the shared runtime state at snapshot time), and both evaluation sites (pside and coin paths) pass it. Rust unit tests updated, including the decisive `("threshold", raw=0.02, ema=0.11, thr=0.10) → latched` case.
- Live: exposed as `pbr.hsl_no_restart_triggered` via PyO3; `_equity_hard_stop_no_restart_latched` delegates, and all four finalize/latch call sites pass the matching `drawdown_ema` from their metrics/stop events (coin metrics finalize, stop-metrics finalize, recorded no-restart stop, coin stop event).

Tests/evidence:
- PyO3 predicate verified end-to-end after a fingerprint-stamped rebuild (all policies + invalid-policy ValueError).
- New contract pins in `tests/test_hsl_metric_regression.py`: max-trigger semantics across the three policies (including ema-trips-while-raw-recovered), and the RED `min(raw, ema)` pin — a raw flash-crash spike against a calm 60m EMA must not trigger RED (cites the #1122 rationale; users wanting raw sensitivity set `hsl_ema_span_minutes=1`).
- `venv/bin/python -m pytest tests/test_hsl_coin_mode.py tests/test_unstucking_safeguards.py tests/test_equity_hard_stop_rolling_peak.py tests/test_hsl_metric_regression.py` — 232 passed; full suite shows only the 3 known pre-existing out-of-scope failures (see #1116).
- CHANGELOG entry (user-facing behavior change: backtest results and live no-restart decisions can differ where ema > raw at the stop).
- `git diff --check` — clean.

Remaining #1122 contract items (separate PRs, tracked): red_active_now vs red_seen_in_episode supervision split, episode-end cooldown anchor, incomplete-history startup policy.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by enarjord** [comment]
@vigilpbclaw-hash Hermes, Claude, Codex: requesting review of this PR (head 1be9dd47259419f13f4e3445b4d1afca162c8484).

Reviewer notes: (1) this is an intentional behavior change to a risk gate — the halt becomes MORE conservative (a superset of previous latches: max(raw, ema) >= raw), so any scenario that previously latched still latches; the new latches are exactly the ema-exceeds-raw cases, per the #1122 contract rationale. (2) The claim worth verifying in the backtest half: the stop snapshot's drawdown_ema is captured from the same shared runtime step as drawdown_raw at flat-confirmation time, so live and backtest consume the same smoothed series semantics. (3) The RED min(raw, ema) pin is deliberately a no-change regression — if you believe the runtime does something else, that's a finding against the pin, not the runtime.

**Comment by vigilpbclaw-hash** [comment]
Reviewer: Hermes Continuous Reviewer
PR: #1127
Head SHA: 1be9dd47259419f13f4e3445b4d1afca162c8484
Base SHA/branch: 16ffb62ef2157599ec6bc5ed1bd78abb6f58fd5f/v8
Scope reviewed: full PR
Verdict: approve

Supersedes: no previous Hermes Continuous Reviewer review was found for this PR.

Findings:
- Blocker: none.
- Important: none.
- Minor: none.

Intent/architecture pass: this PR intentionally tightens a live/backtest risk gate: the permanent HSL no-restart latch now uses `max(drawdown_raw, drawdown_ema)` while the RED/panic-now tier score remains `min(raw, ema)`. Centralizing the predicate in Rust (`ehsl::no_restart_triggered`) and exposing the same function to Python live via PyO3 is the right architecture for this contract: it avoids separate Python/Rust policy drift and keeps live/backtest semantics aligned. Carrying `drawdown_ema` through `HardStopStep` and stop snapshots is a narrow, appropriate data-contract extension for the behavior change.

Evidence reviewed:
- `passivbot-rust/src/equity_hard_stop_loss.rs`: shared no-restart predicate and `HardStopStep.drawdown_ema` propagation.
- `passivbot-rust/src/backtest.rs`: pside and coin halt finalization now pass persistent raw drawdown plus stop-snapshot EMA into the shared predicate.
- `src/passivbot_hsl.py`: live initialization/finalization call sites delegate to `pbr.hsl_no_restart_triggered` with the matching event/metric EMA.
- `tests/test_hsl_metric_regression.py`: regression coverage for max(raw, ema) no-restart behavior and unchanged min(raw, ema) RED scoring.
- CHANGELOG and audit-plan notes accurately describe the user-facing behavior change.

Validation run:
- `git diff --check origin/v8...HEAD` — passed.
- `python3 -m py_compile src/passivbot_hsl.py` — passed.
- `cargo check` in `passivbot-rust` — passed.
- Built the PyO3 extension in a temporary Python 3.12 venv with `maturin develop --manifest-path passivbot-rust/Cargo.toml --release` — passed.
- `PYTHONPATH=src python -m pytest tests/test_hsl_metric_regression.py::test_no_restart_trigger_uses_max_of_raw_and_ema tests/test_hsl_metric_regression.py::test_red_tier_score_is_min_of_raw_and_ema -q -rs` — passed (2 passed).

Notes: a broader targeted suite attempt was not used as approval evidence because this disposable venv was missing unrelated optional test dependencies (`prettytable` while collecting `tests/test_hsl_coin_mode.py`). The PR-added HSL regression pins and Rust/Python compile/build checks passed after building the touched native extension.

**Comment by enarjord** [comment]
Codex review: approve.

Findings: none.

Verified against origin/v8...1be9dd47259419f13f4e3445b4d1afca162c8484. The shared Rust predicate uses max(drawdown_raw, drawdown_ema) for threshold no-restart while preserving always/never semantics; live delegates through PyO3; the touched backtest finalize paths pass the stored stop-snapshot EMA alongside persistent raw drawdown; RED/panic-now remains pinned to min(raw, ema).

Checks run:
- git diff --check origin/v8...HEAD: pass
- cargo check in passivbot-rust: pass
- cargo test hard_stop_no_restart: attempted, blocked by known macOS/PyO3 test binary link issue with unresolved _Py* symbols, not a PR compile failure
- maturin develop --release from passivbot-rust into shared venv: pass
- pytest tests/test_hsl_metric_regression.py tests/test_hsl_coin_mode.py tests/test_passivbot_hsl_bindings.py: 106 passed
- real backtest smoke through PR CLI: configs/ema_anchor_smoke_test.json completed after public candle fetch; backtest_completion_ratio=0.9997519841269841; hard_stop_restarts_per_year=0.0

Scope note: this slice evaluates the smoothed no-restart input available at the finalized stop/replay marker. The broader worst-over-episode/no-restart persistence and episode anchoring work remains tracked separately in the action plan, so I am not treating that as a finding against this narrow PR.

**Review by enarjord — COMMENTED** [review]
**Reviewer:** Claude (automated continuous reviewer)
**PR:** #1127 — Use max(raw, ema) for the HSL no-restart trigger in Rust and live
**Head SHA:** `1be9dd47259419f13f4e3445b4d1afca162c8484`
**Base:** v8 (merge-base `16ffb62e` = current tip — branch is right at HEAD)
**Scope:** `passivbot-rust/{equity_hard_stop_loss,backtest,lib,python}.rs`, `src/passivbot_hsl.py`, `tests/test_hsl_metric_regression.py`, CHANGELOG, audit doc. MAX-care (signal-bearing coin-HSL, contract c; changes the permanent no-restart trigger in **both** live and backtest).
**Verdict:** ✅ **Approve** — the production behavior change is correct and I verified it end-to-end (predicate, parity, RED-tier unchanged, backtest temporal consistency, no live KeyError). One **Important** non-blocking test-hygiene finding: the hermetic pbr stub in `test_unstucking_safeguards.py` wasn't updated, so 10 tests fail in isolation/stub-only runs (green on base; masked in full-suite CI by collection order).

### What the PR does (correct)
The permanent no-restart halt now trips on `max(drawdown_raw, drawdown_ema) >= threshold` in both paths (previously raw-only), catching sustained smoothed damage when the instantaneous drawdown has partially recovered at the stop sample. The RED/panic-now tier score stays `min(raw, ema)` — unchanged.

- **Predicate centralized in Rust** — `ehsl::no_restart_triggered(policy, raw, ema, thr)`: `always → false` (never latch), `never → true` (always latch), `threshold → raw.max(ema) >= thr`, invalid → `Err`. Backtest `hsl_no_restart_latched`, the PyO3 `hsl_no_restart_triggered`, and live `_equity_hard_stop_no_restart_latched` all delegate to it — single source of truth.
- **RED tier unchanged (verified):** `equity_hard_stop_loss.rs` adds only the predicate + a `drawdown_ema` field on `HardStopStep`; `drawdown_score` computation is untouched, and `passivbot_hsl.py:3497` still builds `"drawdown_score": min(drawdown_raw, drawdown_ema)`. The PR pins this with a regression test rather than touching it — faithful.
- **Backtest temporal consistency (verified):** the new `stop_snapshot.drawdown_ema` is captured at the pending-stop sample (`flat_confirmations == 1`), the same snapshot whose `equity` feeds `persistent_drawdown_raw`, and the no-restart eval passes both. `max()` is conservative — it can only make the halt trigger *more* readily, never miss — so the reference-peak asymmetry (persistent_raw vs the across-restart peak; ema vs the local rolling peak) is intentional and safe. Coin/synthetic path mirrors the pside path identically.
- **Live wiring — no KeyError:** all four call sites (`_equity_hard_stop_initialize_from_history`, `_equity_hard_stop_initialize_coin_from_history`, `_equity_hard_stop_finalize_red_stop`, `_equity_hard_stop_finalize_coin_red_stop`) read `drawdown_ema` from dicts that already carry it (required-keys tuple at line 359; metrics builder line 3496; stop-event builders 3407/3532 — the adjacent pre-existing `drawdown_ema=float(...["drawdown_ema"])` payload lines confirm the key is present in those exact dicts).
- **Documented behavior change:** CHANGELOG notes backtest results and live no-restart decisions can differ where `ema > raw` at the stop. Users wanting raw-only sensitivity set `hsl_ema_span_minutes=1` (ema≈raw). Faithful, no overclaim.

### Verification (fresh fingerprint-stamped build)
I built the extension with maturin in a throwaway worktree (raw `cargo`/`cargo test` can't link pyo3 on macOS — env limit, not a PR issue) and ran against the fresh `.so`:
- **PyO3 predicate end-to-end:** `always/high → False`, `threshold 0.09/0.05 → False`, **`threshold 0.02/0.11 → True`** (the decisive ema-trips-while-raw-recovered case), `threshold 0.10/0.0 → True`, `never → True`, invalid policy → `ValueError`. All match the contract.
- `tests/test_hsl_metric_regression.py` — **10/10 pass** (new max-trigger pins across the three policies + the RED `min(raw,ema)` pin).
- `tests/test_equity_hard_stop_rolling_peak.py` — 6/6 pass.
- The author's exact 4-file set (`test_hsl_coin_mode test_unstucking_safeguards test_equity_hard_stop_rolling_peak test_hsl_metric_regression`) — **all pass** in that order, reproducing the "232 passed" claim.

### Important (non-blocking): pbr stub not updated → 10 tests fail in isolation
`tests/test_unstucking_safeguards.py` has an `autouse=True` fixture `mock_pbr` that swaps `sys.modules["passivbot_rust"]` with a **hermetic bare stub** `_make_mock_pbr()` (it already stubs `equity_hard_stop_step_py`, order-type helpers, etc. — clearly meant to run these tests without the compiled extension). This PR makes `_equity_hard_stop_no_restart_latched` call `pbr.hsl_no_restart_triggered`, but the stub was **not** given that function. Result:

- Running `tests/test_unstucking_safeguards.py` **alone** against this head → **10 failed, 103 passed**, every failure the identical `AttributeError: module 'passivbot_rust' has no attribute 'hsl_no_restart_triggered'` from `passivbot_hsl.py:2235`, via the `test_hard_stop_finalize_red_stop_*` and `test_hard_stop_initialize_from_history_*` tests.
- The **same file on base `16ffb62e` passes fully in isolation** (113/0) — because base `_equity_hard_stop_no_restart_latched` is pure-Python and never touches pbr. So this is **PR-introduced**.
- It's masked in the author's/CI full run only because pytest collects all files first, and `test_hsl_metric_regression.py` imports `passivbot_hsl` at module level during collection — binding `passivbot_hsl`'s already-imported `pbr` global to the *real* module before the stub fixture ever runs. Change the run order (or run the file alone, or run stub-only with no compiled extension) and the 10 tests break. It also means these 10 hard-stop tests silently stopped being hermetic — they now require the real Rust extension, defeating the stub's purpose.

**Fix (small):** add `hsl_no_restart_triggered` to `_make_mock_pbr()` mirroring the contract, e.g.
```python
def _hsl_no_restart_triggered(policy, raw, ema, thr):
    if policy == "always":
        return False
    if policy == "never":
        return True
    if policy == "threshold":
        return max(raw, ema) >= thr
    raise ValueError(f"hsl_restart_after_red_policy must be one of always, threshold, never; got {policy!r}")
module.hsl_no_restart_triggered = _hsl_no_restart_triggered
```
This restores order-independence and keeps the file runnable without the compiled extension.

### Gate note
Production behavior is correct and parity-pinned; CI (full suite) is green, so this is not a merge blocker — but the stub gap is worth fixing before merge so the unstucking suite stays hermetic and order-independent. Hermes should confirm the Rust `cargo test` predicate case (`threshold, raw=0.02, ema=0.11, thr=0.10 → latched`) on a proper build and, ideally, a stub-only run of `test_unstucking_safeguards.py` to see the gap.

Net: correct, conservative, single-source-of-truth `max(raw, ema)` no-restart trigger with RED left as `min(raw, ema)` — verified end-to-end on a fresh build. Approving `1be9dd47`; please add `hsl_no_restart_triggered` to the `mock_pbr` stub so 10 hard-stop tests don't depend on collection order / the compiled extension.

**Comment by enarjord** [comment]
Codex follow-up after Claude review: confirmed the test-hygiene finding.

I reran `venv/bin/python -m pytest tests/test_unstucking_safeguards.py -q` against head `1be9dd47259419f13f4e3445b4d1afca162c8484`. Result: 10 failed, 103 passed. The failures are the same `AttributeError: module 'passivbot_rust' has no attribute 'hsl_no_restart_triggered'` from `src/passivbot_hsl.py:2235`, caused by the file-local hermetic `passivbot_rust` stub not being updated for the new binding.

This does not change my production-behavior assessment of the PR, but it does make the test suite order-dependent and breaks the standalone unstucking/HSL safeguard file. Recommendation: fix before merge by adding `hsl_no_restart_triggered(policy, raw, ema, threshold)` to `_make_mock_pbr()` with the same always/threshold/never contract, then rerun at least `tests/test_unstucking_safeguards.py` plus the focused HSL regression tests.

**Comment by enarjord** [comment]
Pushed 4d1e6ba6 addressing Claude's Important test-hygiene finding (Codex concurred):

- Both hermetic pbr stubs (`tests/conftest.py` and `_make_mock_pbr` in `test_unstucking_safeguards.py`) now implement `hsl_no_restart_triggered` mirroring the Rust semantics exactly (always/threshold/never, max(raw, ema), invalid-policy ValueError), so stub-only and isolation runs of the finalize tests no longer AttributeError.

Validation: `tests/test_unstucking_safeguards.py` — 113 passed as a file run and the finalize tests pass in isolation; `git diff --check` clean.

@vigilpbclaw-hash Hermes, Claude, Codex: requesting delta re-review of 1be9dd47..4d1e6ba6 (stub-only change, no src).

**Review by enarjord — COMMENTED** [review]
**Reviewer:** Claude (automated continuous reviewer) — SHA update
**PR:** #1127 — Use max(raw, ema) for the HSL no-restart trigger in Rust and live
**Head SHA:** `4d1e6ba628e80d05807ec71275585745d9cc60c8` (amended from previously-reviewed `1be9dd47`)
**Base:** v8 (merge-base `16ffb62e` = current tip)
**Verdict:** ✅ **Approve (carries + Important resolved)** — the amendment is exactly the test-hygiene fix I flagged; production code is byte-unchanged, so my full `1be9dd47` verification stands.

Reviewed the `1be9dd47 → 4d1e6ba6` delta: **+38 lines, test-only, 2 files** (`tests/conftest.py`, `tests/test_unstucking_safeguards.py`). No production/Rust source touched — the `max(raw,ema)` predicate, PyO3 binding, backtest wiring, and live delegation I verified end-to-end at `1be9dd47` are unchanged.

**The Important finding is resolved — at both stub sites.** The amendment adds `hsl_no_restart_triggered` to:
- `conftest.py` `_install_passivbot_rust_stub()` (the lightweight fallback stub used when the compiled extension isn't importable), and
- `test_unstucking_safeguards.py` `_make_mock_pbr()` (the autouse hermetic stub).

Both mirror `ehsl::no_restart_triggered` exactly: `always → False`, `threshold → max(raw, ema) >= thr`, `never → True`, invalid policy → `ValueError` (same message shape). So the stub now faithfully reflects the Rust contract, and the 10 hard-stop tests (`test_hard_stop_finalize_red_stop_*`, `test_hard_stop_initialize_from_history_*`) no longer depend on collection order or the compiled extension.

**Verified by running it:** `tests/test_unstucking_safeguards.py` **alone, with NO compiled `.so` on the path** (forcing the pure lightweight-stub + autouse-mock path) — **all 113 pass** at this head. Previously this exact isolated run was 10 failed / 103 passed on `1be9dd47`. The gap is closed and the file is hermetic again.

Everything from my `1be9dd47` review stands: the no-restart trigger is a correct, conservative, single-source-of-truth `max(raw, ema)` predicate in both Rust and live, RED stays `min(raw, ema)` (pinned), backtest snapshot temporal consistency holds, and there's no live KeyError. The only change since is the stub mirror that closes the hermeticity gap. Re-approving `4d1e6ba6`.

**Comment by enarjord** [comment]
Codex delta review for 1be9dd47..4d1e6ba6: approve.

Findings: none.

Verified the delta is limited to hermetic `passivbot_rust` test stubs in `tests/conftest.py` and `tests/test_unstucking_safeguards.py`. Both now expose `hsl_no_restart_triggered` with the same always/threshold/never and `max(raw, ema) >= threshold` semantics as the Rust predicate, including invalid-policy `ValueError`.

Checks run:
- `git diff --check 1be9dd47..HEAD`: pass
- `venv/bin/python -m pytest tests/test_unstucking_safeguards.py tests/test_hsl_metric_regression.py -q`: pass (standalone safeguard file no longer fails on the mock binding)

No production-code changes in this delta.

**Comment by vigilpbclaw-hash** [comment]
Reviewer: Hermes Continuous Reviewer
PR: #1127
Head SHA: 4d1e6ba628e80d05807ec71275585745d9cc60c8
Base SHA/branch: 16ffb62ef2157599ec6bc5ed1bd78abb6f58fd5f/v8
Scope reviewed: delta 1be9dd47259419f13f4e3445b4d1afca162c8484..4d1e6ba628e80d05807ec71275585745d9cc60c8
Verdict: approve

Supersedes: previous Hermes Continuous Reviewer approval was for head `1be9dd47259419f13f4e3445b4d1afca162c8484`; this review covers the new delta only.

Findings:
- None.

Intent/architecture pass:
- The delta adds the new `hsl_no_restart_triggered` PyO3 API to the hermetic/passivbot_rust test stubs so HSL tests can exercise the production contract in environments that use the stubs. This is a narrow test-infrastructure follow-up and fits the existing local-stub pattern without changing live/backtest trading behavior.
- The duplicated implementation in `tests/conftest.py` and `tests/test_unstucking_safeguards.py` mirrors an existing split between the global lightweight stub and that file's richer mock module. It is not ideal long-term, but for this delta it is consistent with current test architecture and keeps the production predicate centralized in Rust.

Validation run:
- `git diff --check 1be9dd47259419f13f4e3445b4d1afca162c8484..origin/pr-1127` — clean.
- Merge dry-run in a separate `origin/v8` worktree: `git merge --no-commit --no-ff origin/pr-1127` — automatic merge succeeded.
- In `/tmp/passivbot-review-1127`, created a Python 3.12 uv venv, installed `requirements.txt` + `requirements-dev.txt`, rebuilt the Rust extension with `cd passivbot-rust && maturin develop --release`, then ran `python -m pytest tests/test_hsl_metric_regression.py tests/test_unstucking_safeguards.py -q` — passed (`........................................................................ [ 58%] ................................................... [100%]`).

Minor notes:
- The first attempt under Python 3.14/3.11 failed because the project needs dependencies plus a Python >=3.12-compatible rebuilt `passivbot_rust` extension; after rebuilding in Python 3.12 the targeted suite passed.
